In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r'C:\Users\USER\Documents\re-integration\datasets\weather_data.xls')
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        7.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08         31.0        2.0   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [10]:
type(df.day)

pandas.Series

In [8]:
new_df = df.fillna(0)
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          0.0        7.0   Sunny
2 2017-01-05         28.0        0.0    Snow
3 2017-01-06          0.0        7.0       0
4 2017-01-07         32.0        0.0    Rain
5 2017-01-08         31.0        2.0   Sunny
6 2017-01-09          0.0        0.0       0
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [11]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='str')

In [12]:
new_df = df.fillna({
    'temperature' : 30,
    'windspeed' : 5.0,
    'event' : 'Sunny'
})
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         30.0        7.0   Sunny
2 2017-01-05         28.0        5.0    Snow
3 2017-01-06         30.0        7.0   Sunny
4 2017-01-07         32.0        5.0    Rain
5 2017-01-08         31.0        2.0   Sunny
6 2017-01-09         30.0        5.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [14]:
new_df = df.ffill()
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        7.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         28.0        7.0    Snow
4 2017-01-07         32.0        7.0    Rain
5 2017-01-08         31.0        2.0   Sunny
6 2017-01-09         31.0        2.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [21]:
new_df = df.bfill(axis=0, limit=1)
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        7.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        2.0    Rain
5 2017-01-08         31.0        2.0   Sunny
6 2017-01-09         34.0        8.0  Cloudy
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [4]:
event = df[['event','day']]
event

    event        day
0    Rain 2017-01-01
1   Sunny 2017-01-04
2    Snow 2017-01-05
3     NaN 2017-01-06
4    Rain 2017-01-07
5   Sunny 2017-01-08
6     NaN 2017-01-09
7  Cloudy 2017-01-10
8   Sunny 2017-01-11

In [5]:
new_df = df.drop('event', axis=1)
new_df

         day  temperature  windspeed
0 2017-01-01         32.0        6.0
1 2017-01-04          NaN        7.0
2 2017-01-05         28.0        NaN
3 2017-01-06          NaN        7.0
4 2017-01-07         32.0        NaN
5 2017-01-08         31.0        2.0
6 2017-01-09          NaN        NaN
7 2017-01-10         34.0        8.0
8 2017-01-11         40.0       12.0

In [6]:
new_df = new_df.set_index('day')

In [7]:
new_df = new_df.interpolate(method='time')
new_df

            temperature  windspeed
day
2017-01-01         32.0        6.0
2017-01-04         29.0        7.0
2017-01-05         28.0        7.0
2017-01-06         30.0        7.0
2017-01-07         32.0        4.5
2017-01-08         31.0        2.0
2017-01-09         32.5        5.0
2017-01-10         34.0        8.0
2017-01-11         40.0       12.0

In [8]:
df_concat = pd.merge(new_df,event, on='day', )
df_concat

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         29.0        7.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         30.0        7.0     NaN
4 2017-01-07         32.0        4.5    Rain
5 2017-01-08         31.0        2.0   Sunny
6 2017-01-09         32.5        5.0     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [9]:
df_concat.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='str')

In [10]:
columns = ['temperature', 'windspeed', 'event']
new_df = df.dropna(subset=columns,how= 'all')
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        7.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08         31.0        2.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
new_df = df.dropna()
new_df

In [ ]:
new_df = df.dropna(how='all')
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        7.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08         31.0        2.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [28]:
new_df = df.dropna(thresh=2)
new_df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        7.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08         31.0        2.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [11]:
import numpy as np

In [16]:
df = pd.read_csv(r'C:\Users\USER\Documents\re-integration\datasets\weather_data.csv')
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [22]:
df.replace([-99999,-88888],np.nan)

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  no event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny
6  1/6/2017         34.0        NaN  no event

In [26]:
df.replace({
    -99999 : 0 ,
    -88888 : 0,
    'no event' : 'Sunny'    
})

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017            0          7  Sunny
2  1/3/2017           28          0   Snow
3  1/4/2017            0          7  Sunny
4  1/5/2017           32          0   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          0  Sunny

In [20]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='str')

In [25]:
df.replace({
    'temperature' : -99999 ,
    'windspeed' : [-99999,-88888],
    'event' : 'no event'    
},np.nan)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        NaN    NaN