In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('C:/Users/USER/Documents/re-integration/datasets/movies.csv')
df.head(5)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [4]:
df.describe()

       release_year  imdb_rating        budget        revenue
count     37.000000    36.000000     37.000000      37.000000
mean    2007.027027     7.919444   2084.975135    4117.135135
std       17.657995     1.204947  11477.487145   16372.462682
min     1946.000000     1.900000      1.000000       3.100000
25%     2001.000000     7.800000     15.500000     263.100000
50%     2014.000000     8.100000    165.000000     701.800000
75%     2018.000000     8.400000    250.000000    2000.000000
max     2022.000000     9.300000  70000.000000  100000.000000

In [6]:
df.shape

(37, 10)

In [7]:
df.columns

Index(['title', 'industry', 'release_year', 'imdb_rating', 'studio', 'budget',
       'revenue', 'unit', 'currency', 'language'],
      dtype='str')

In [8]:
df[df.imdb_rating == df.imdb_rating.max()]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English

In [ ]:
df.sample(4)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English

In [3]:
column = ['industry', 'release_year', 'imdb_rating', 'studio', 'budget','revenue']

In [14]:
# column = ['industry', 'release_year', 'imdb_rating', 'studio', 'budget','revenue']
df.loc[[0],column]

,industry,release_year,imdb_rating,studio,budget,revenue
0,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0

In [10]:
id_columns = df.columns.get_indexer(column)
id_columns

array([1, 2, 3, 4, 5, 6])

In [12]:
df.iloc[29:,id_columns]

     industry  release_year  imdb_rating               studio  budget  revenue
29  Bollywood          2022          8.3          Zee Studios   250.0   3409.0
30  Bollywood          2015          8.1    Salman Khan Films   900.0  11690.0
31  Bollywood          2018          1.9    Salman Khan Films     1.8      3.1
32  Bollywood          2021          8.4   Dharma Productions   500.0    950.0
33  Bollywood          2022          8.4        Hombale Films     1.0     12.5
34  Bollywood          2021          7.6  Mythri Movie Makers     2.0      3.6
35  Bollywood          2022          8.0    DVV Entertainment     5.5     12.0
36  Bollywood          2015          8.0     Arka Media Works     1.8      6.5

In [31]:
df[columns]

,industry,release_year,imdb_rating,studio,budget,revenue
0,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0
1,Hollywood,2022,7.0,Marvel Studios,200.00,954.8
2,Hollywood,2013,6.8,Marvel Studios,165.00,644.8
3,Hollywood,2017,7.9,Marvel Studios,180.00,854.0
4,Hollywood,2022,6.8,Marvel Studios,250.00,670.0
5,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3
6,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8
7,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1
8,Hollywood,2000,8.5,Universal Pictures,103.00,460.5
9,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0
10,Hollywood,1946,8.6,Liberty Films,3.18,3.3
11,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0
12,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0
13,Hollywood,2008,9.0,Syncopy,185.00,1006.0
14,Hollywood,1993,9.0,Universal Pictures,22.00,322.2
15,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0
16,Hollywood,2019,8.5,NaN,15.50,263.1
17,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0
18,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0
19,Hollywood,2011,6.9,Marvel Studios,216.70,370.6
20,Hollywood,2014,7.8,Marvel Studios,177.00,714.4
21,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0
22,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0
23,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0
24,Bollywood,2015,7.2,NaN,1.40,3.5
25,Bollywood,2007,8.3,NaN,120.00,1350.0
26,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0
27,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0
28,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9
29,Bollywood,2022,8.3,Zee Studios,250.00,3409.0
30,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0
31,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1
32,Bollywood,2021,8.4,Dharma Productions,500.00,950.0
33,Bollywood,2022,8.4,Hombale Films,1.00,12.5
34,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6
35,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0
36,Bollywood,2015,8.0,Arka Media Works,1.80,6.5

In [22]:
df.loc[[0],columns]

,industry,release_year,imdb_rating,studio,budget,revenue
0,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0

In [13]:
df_w = pd.read_csv(r'C:\Users\USER\Documents\re-integration\datasets\weather_by_cities.csv')
df_w.head()

        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
4  1/1/2017    mumbai           90          5  Sunny

In [14]:
temp = df_w.groupby('city')
temp

In [10]:
for city,df_w in temp:
    print(f'{city},: max temperature ={df_w.temperature.max()}  avg windspeed ={df_w.windspeed.mean()} ')

mumbai,: max temperature =92  avg windspeed =9.25
new york,: max temperature =36  avg windspeed =8.0
paris,: max temperature =54  avg windspeed =12.75

In [15]:
temp.min()

               day  temperature  windspeed   event
city
mumbai    1/1/2017           85          5     Fog
new york  1/1/2017           28          6    Rain
paris     1/1/2017           42          8  Cloudy

In [16]:
temp.max()

               day  temperature  windspeed  event
city
mumbai    1/4/2017           92         15  Sunny
new york  1/4/2017           36         12  Sunny
paris     1/4/2017           54         20  Sunny

In [8]:
df_1 = pd.DataFrame({
    'name' : ['jaden','micheal','daniel'],
    "ages" : [22,32,12],
    "scores" : [4.2,4.0,3.99]
},index=[0,1,2])
df_1

      name  ages  scores
0    jaden    22    4.20
1  micheal    32    4.00
2   daniel    12    3.99

In [9]:
df_2 = pd.DataFrame({
    'name' : ['micheal','jaden','daniel'],
    "courses" : ['creative','bussiness','architect']
},index=[1,0,2])
df_2

      name    courses
1  micheal   creative
0    jaden  bussiness
2   daniel  architect

In [10]:
pd.concat([df_1,df_2], axis = 1, )

      name  ages  scores     name    courses
0    jaden    22    4.20    jaden  bussiness
1  micheal    32    4.00  micheal   creative
2   daniel    12    3.99   daniel  architect

In [12]:
pd.concat([df_1,df_2], keys=['igbo','daniel'] )

             name  ages  scores    courses
igbo   0    jaden  22.0    4.20        NaN
       1  micheal  32.0    4.00        NaN
       2   daniel  12.0    3.99        NaN
daniel 1  micheal   NaN     NaN   creative
       0    jaden   NaN     NaN  bussiness
       2   daniel   NaN     NaN  architect

In [13]:
pd.merge(df_1,df_2, on = 'name')

      name  ages  scores    courses
0    jaden    22    4.20  bussiness
1  micheal    32    4.00   creative
2   daniel    12    3.99  architect

In [17]:
df1 = pd.DataFrame({
    "city": ["new york","chicago","orlando", "baltimore"],
    "temperature": [21,14,35, 38],
})
df1

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38

In [18]:
df2 = pd.DataFrame({
    "city": ["chicago","new york","san diego"],
    "humidity": [65,68,71],
})
df2

        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [20]:
pd.merge(df1,df2,on='city',how= 'left')

        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN